### ISSUE TITLE
Purpose of crate?

### ISSUE THREAD

**Issue by bwasty** [unrust/uni-glsl#5]
I see this crate contains GLSL parsing logic, but it's unclear how it relates to the rest of `unrust`.

**Comment by edwin0cheng** [comment]
The main and only reason right now is to support #include and #define macro.

**Comment by jice-nospam** [comment]
to be able to write GLSL that works for both native and wasm

**Comment by bwasty** [comment]
Cool - feel free to close, though I think it may be helpful to add this information to the readme first.

**Comment by edwin0cheng** [comment]
@bwasty Thanks for the feedback, we just added this information to the readme.
